###
GET https://navys-shop-backend.herokuapp.com/api/products

### Get certain product
GET https://navys-shop-backend.herokuapp.com/api/products/630b289d6b2afa8d56858f09


### Add new products
POST https://navys-shop-backend.herokuapp.com/api/products
Content-Type:application/json

{
    "name":"香椒麻麻耗",
    "price":"200",
    "image":"image url here",
    "describe":"高科大出產的椒麻口味香腸",
    "specifications":"淨重300g",
    "delivery_way":"店面選購、冷凍宅配、校內限定公文車交換"
}

### Remove certain product
DELETE  https://navys-shop-backend.herokuapp.com/api/products/630b289d6b2afa8d56858f09


### Update certain product
PATCH  https://navys-shop-backend.herokuapp.com/api/products/630e0cd80f75b650ac6e0b43
Content-Type:application/json

{
    "name":"香椒麻麻耗2",
    "price":"200",
    "image":"image url here",
    "describe":"高科大出產的椒麻口味香腸",
    "specifications":"淨重300g",
    "delivery_way":"店面選購、冷凍宅配、校內限定公文車交換"
}

### 創建會員並發送驗證信

POST https://navys-shop-backend.herokuapp.com/api/members/send
Content-Type:application/json

{
    "email":"C109156135@nkust.edu.tw",
    "password":"asd45628",
    "name":"嗡嗡嗡",
    "address":"高科大出產的椒麻口味香腸",
    "phone_number":"0977"
}

### 驗證會員

GET https://navys-shop-backend.herokuapp.com/api/members/verify/ef9ef1d9-c348-4ca2-b788-1d8122aa8b3d

### 檢視所有會員
GET https://navys-shop-backend.herokuapp.com/api/members

### 刪除會員

DELETE  https://navys-shop-backend.herokuapp.com/api/members/630f1b77251e046f0057a83e