###
GET http://localhost:3000/api/products

### Get certain product
GET http://localhost:3000/api/products/630b289d6b2afa8d56858f09
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiLll6Hll6Hll6EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NjIwMjM4NzYsImV4cCI6MTY2MjkyMzg3Nn0.8Tq_huVynUjz1YYxe2RuyFfPUtLEQyphQTuIBNgbu44; Max-Age=900; Path=/; Expires=Thu, 01 Sep 2022 09:32:56 GMT; HttpOnly


### Add new products
POST http://localhost:3000/api/products
Content-Type:application/json

{
    "name":"香椒麻麻耗",
    "price":"200",
    "image":"image url here",
    "describe":"高科大出產的椒麻口味香腸",
    "specifications":"淨重300g",
    "delivery_way":"店面選購、冷凍宅配、校內限定公文車交換"
}

### Remove certain product
DELETE  http://localhost:3000/api/products/630b1d2960c70b97bd7c1162


### Update certain product
PATCH  http://localhost:3000/api/products/630b1cb584428c46083ac825
Content-Type:application/json

{
    "name":"香椒麻麻耗2",
    "price":"200",
    "image":"image url here",
    "describe":"高科大出產的椒麻口味香腸",
    "specifications":"淨重300g",
    "delivery_way":"店面選購、冷凍宅配、校內限定公文車交換"
}

### 創建會員並發送驗證信

POST http://localhost:3000/api/members/send
Content-Type:application/json

{
    "email":"C109156135@nkust.edu.tw",
    "password":"asd45628",
    "name":"test",
    "address":"test",
    "phone_number":"0977"
}

### 檢視所有會員
GET http://localhost:3000/api/members
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiLll6Hll6Hll6EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NjIwMjM4NzYsImV4cCI6MTY2MjkyMzg3Nn0.8Tq_huVynUjz1YYxe2RuyFfPUtLEQyphQTuIBNgbu44; Max-Age=900; Path=/; Expires=Thu, 01 Sep 2022 09:32:56 GMT; HttpOnly

### 會員登入
GET http://localhost:3000/api/members/login
Content-Type:application/json

{
    "email":"C109156135@nkust.edu.tw",
    "password":"asd45628"
}

### 刪除會員

DELETE  http://localhost:3000/api/members/630f5e31ddadc5db190ee9dc