### 取得全部產品
GET http://localhost:3000/api/products/

### 取得部分產品
GET http://localhost:3000/api/products/p?page=1

### Get certain product
GET http://localhost:3000/api/products/630b296af602d9b5b05b62b7

### Add new products
POST http://localhost:3000/api/products
Content-Type:application/json

{
    "name":"香椒麻麻耗",
    "price":"200",
    "image":"image url here",
    "describe":"高科大出產的椒麻口味香腸",
    "specifications":"淨重300g",
    "delivery_way":"店面選購、冷凍宅配、校內限定公文車交換"
}

### Remove certain product
DELETE  http://localhost:3000/api/products/630b1d2960c70b97bd7c1162


### Update certain product
PATCH  http://localhost:3000/api/products/630b1cb584428c46083ac825
Content-Type:application/json

{
    "name":"香椒麻麻耗2",
    "price":"200",
    "image":"image url here",
    "describe":"高科大出產的椒麻口味香腸",
    "specifications":"淨重300g",
    "delivery_way":"店面選購、冷凍宅配、校內限定公文車交換"
}

### 創建會員並發送驗證信

POST http://localhost:3000/api/members/send
Content-Type:application/json

{
    "email":"C109156135@nkust.edu.tw",
    "password":"asd45628",
    "name":"test",
    "address":"test",
    "phone_number":"0977"
}

### 檢視所有會員
GET http://localhost:3000/api/members

### 會員登入
GET http://localhost:3000/api/members/login
Content-Type:application/json

{
    "email":"C109156135@nkust.edu.tw",
    "password":"asd45628"
}

### 刪除會員

DELETE  http://localhost:3000/api/members/630f5e31ddadc5db190ee9dc

### 測試查看

GET  http://localhost:3000/api/test/

### 新增測試

POST  http://localhost:3000/api/test/
Content-Type:application/json

{
    "detail":"test"
}

### 測試刪除

DELETE   http://localhost:3000/api/test/63133198c29ee5e89afb0860

### 供應商測試

GET  http://localhost:3000/api/suppliers/

### 供應商新增

POST  http://localhost:3000/api/suppliers/
Content-Type:application/json

{
        "supid":"123",
        "supname":"123name",
        "supaddr":"123addr",
        "supphone":"099562846",
        "supemail":"123mail",
        "supworkarea":"123area",
        "supcontactman":"123man"
}
